<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="cubesat">
    
    <xacro:include filename="cubesat_include.xacro" />


    <!--  -->
    
    <link name="world"></link>
    
    <joint name="1U_joint" type="floating">
    	<origin xyz="0 0 0" rpy="0 0 0"/>
    	<parent link="world"/>
    	<child link="1U_link"/>
    </joint>
    
    <link name="1U_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${U_aresta} ${U_aresta} ${U_aresta}" />
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${U_aresta} ${U_aresta} ${U_aresta}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="1" x="0.1" y="0.1" z="0.1">
            <origin xyz="0 0 0.0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
    <!--  -->

    <joint name="camera_joint" type="fixed">
        <origin xyz="${(U_aresta+cam_len)/2} 0 0" rpy="0 0 0"/>
        <parent link="1U_link"/>
        <child link="camera_link"/>
    </joint>
    
    <link name="camera_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${cam_radius}" length="${cam_len}"/>
            </geometry>
		<material name="gray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder radius="${cam_radius}" length="${cam_len}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${cam_mas}" length="${cam_len}"  radius="${cam_radius}">
            <origin xyz="0 0 0.0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <!--  -->
    
	<joint name="RDR3_joint" type="continuous">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<parent link="1U_link"/>
		<child link="RDR3_link"/>
		<axis xyz ="0 0 1" rpy = "0 0 0"/>
		<limit effort="10000" velocity="10000"/>
		<joint_properties damping ="0.0" friction="0.0"/>
	</joint>

    <link name="RDR3_link">
        <visual>
            <origin xyz="0 0 -${(U_aresta+RDR_length)/2}" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="${RDR_radius}" length="${RDR_length}"/>
		</geometry>
	 <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 -${(U_aresta+RDR_length)/2}" rpy="0 0 0"/>
		<geometry>
			<cylinder radius="${RDR_radius}" length="${RDR_length}"/>
		</geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 -${(U_aresta+RDR_length)/2}" rpy="0 0 0"/>
            <mass value="${RDR_mass}" />
            <inertia ixx="${(1/12) * RDR_mass * (3*RDR_radius*RDR_radius + RDR_length*RDR_length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * RDR_mass * (3*RDR_radius*RDR_radius + RDR_length*RDR_length)}" iyz="0.0"
                    izz="${(1/2) * RDR_mass * (RDR_radius*RDR_radius)}" />
        </inertial>
    </link>


    <xacro:include filename="cubesat_gazebo.xacro" />
    <xacro:include filename="cubesat_rdr_control.xacro" /> 


</robot>
