cubesat:
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 1000

  joint_motor_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
          - RDR3_joint

      gains:
          RDR3_joint: {p: 1, i: 0, d: 1}


